#!/usr/bin/env bash
# 404 Not Found
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sed -i '/server_name _;/ a error_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\troot /var/www/html;\n\tinternal;\n\t}' /etc/nginx/sites-available/default
sudo service nginx restart
