#!/usr/bin/env bash
# Double the number of webservers
# Configure the web server 02 identical to web server 01
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i '/server_name _;/ a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i '/server_name _;/ a error_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\troot /var/www/html;\n\tinternal;\n\t}' /etc/nginx/sites-available/default
sudo sed -i '/server_name _;/ a add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
sudo service nginx restart
