#!/usr/bin/env bash
# Display "bad luck" on 4th iteration, "good luck" on 8th and "Holberton School" on others
i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	i=$(( i+1 ))
done
