#!/usr/bin/env bash
# Display information about the holbertonschool file.
FILE="holbertonschool"

if [ -e "$FILE" ]
then
	echo "holbertonschool file exists"
	if [ -s "$FILE" ]
	then
		echo "holbertonschool is not empty"
	else
		echo "holbertonschool is empty"
	fi
	if [ -f "$FILE" ]
	then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
