#!/usr/bin/env bash
# Display information about the holbertonschool file.
FILE="holbertonschool"
if [ -e "$FILE" ];
then
	echo "$FILE file exists"
	if [ -s $FILE ]
	then
		echo "$FILE is not empty"
	else
		echo "$FILE is empty"
	fi
	if [ -f "$FILE" ]
	then
		echo "$FILE is a regular file"
	fi
else
	echo "$FILE file does not exist"
fi
